<a href="https://colab.research.google.com/github/SampathJyotsna-coder/Practice/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calculation of time

In [1]:
L=range(1000)
%timeit [ i**2 for i in L]

131 µs ± 29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [2]:
import numpy as np
a=np.arange(1000)
%timeit a**2

1.6 µs ± 349 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Creation of arrays

In [3]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [4]:
a.ndim,a.shape,len(a)

(1, (4,), 4)

In [6]:
b=np.array([[0,1,2],[3,4,5]])
print(b)
b.ndim,b.shape,len(b)

[[0 1 2]
 [3 4 5]]


(2, (2, 3), 2)

In [10]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
c.ndim,c.shape,c
len(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2

In [11]:
a=np.arange(10)
print(a)
b=np.arange(1,9,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


Basic Operations

In [15]:
a=np.linspace(0,1,6)
print(a)
b=np.ones((3,3))
print(b)
c=np.zeros((3,3))
print(c)
d=np.eye(3)
print(d)
e=np.eye(3,2)
print(e)
f=np.diag(np.array([1,2,3,4]))
print(f)
g=np.random.rand(4)
print(g)
h=np.random.randn(4)
print(h)
print(a,b,c,d,e,f,g,h,sep="\n\n")

[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0.94350592 0.03870456 0.65988814 0.5115287 ]
[-0.91021175 -1.24519827  0.96731055  0.73901293]
[0.  0.2 0.4 0.6 0.8 1. ]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[0.94350592 0.03870456 0.65988814 0.5115287 ]

[-0.91021175 -1.24519827  0.96731055  0.73901293]


Types of datatypes

In [18]:
a=np.arange(10)
print(a)
print(a.dtype)
b=np.arange(10,dtype='float64')
print(b)
print(b.dtype)
c=np.zeros((3,3))
print(c)
print(c.dtype)
d=np.array([1+2j,3+4j])
print(d)
print(d.dtype)
e=np.array(['Bonjor','hello','hello'])
print(e)
print(e.dtype)
f=np.array([True,False,True])
print(f)
print(f.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[1.+2.j 3.+4.j]
complex128
['Bonjor' 'hello' 'hello']
<U6
[ True False  True]
bool


Indexing and slicing

In [19]:
a=np.arange(10)
print(a)
print(a[5])
print([a[2:9:3]])
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
5
[array([2, 5, 8])]
[9 8 7 6 5 4 3 2 1 0]


In [20]:
a=np.diag(np.array([1,2,3,4]))
print(a)
print(a[2,2])
print(a[2,1] == a[2][1])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
3
True


In [21]:
a=np.arange(10)
print(a)
a[1:8:2]=10
print(a)
b=np.arange(5)
a[5:]=b[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10  2 10  4 10  6 10  8  9]
[ 0 10  2 10  4  4  3  2  1  0]


In [22]:
a=np.arange(10)
print(a)
print(a[1:8:2])
print(a[5:])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[5 6 7 8 9]


Copies and views

In [27]:
import numpy as np
a=np.arange(10)
print(a)
b=a[::2]
print(b)
print(np.shares_memory(a,b))
b[0]=10
print(b)
print(a)
a=np.arange(10)
c=a[::2].copy()
print(c)
print(np.shares_memory(a,c))
c[0]=10
print(c)
print(a)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]
[0 2 4 6 8]
False
[10  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


Fancy indexing

In [31]:
a=np.random.randint(0,20,15)
print(a)
mask=(a%2==0)
print(mask)
extract_from_a=a[mask]
print(extract_from_a)
print(a)
a[mask]=-1
print(a)
a=np.arange(0,100,10)
print(a)
a[[2,3,2,4,2]]
print(a)
a[[9,7]]=-200
print(a)

[11 16  0 15  2 14 13  8 16  9  4  8 17  3 10]
[False  True  True False  True  True False  True  True False  True  True
 False False  True]
[16  0  2 14  8 16  4  8 10]
[11 16  0 15  2 14 13  8 16  9  4  8 17  3 10]
[11 -1 -1 15 -1 -1 13 -1 -1  9 -1 -1 17  3 -1]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[   0   10   20   30   40   50   60 -200   80 -200]


Numerical Operations

Elementwise operation

In [32]:
import numpy as np
a=np.array([1,2,3,4])
b=np.ones(4)+1
print(a)
print(b)
print(a-b)
print(a+b)
print(a*b)
print(a/b)


[1 2 3 4]
[2. 2. 2. 2.]
[-1.  0.  1.  2.]
[3. 4. 5. 6.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


Comparisions

In [33]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
print(a==b)
print(a>b)
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

[False  True False  True]
[False False  True False]
False
True


Logical operations

In [34]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
np.logical_and(a,b)

[ True  True  True False]
[ True False False False]


array([ True, False, False, False])

Transcendental functions

In [35]:
a=np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


/tmp/ipykernel_3117/3889713356.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


Basic reductions

In [43]:
x=np.array([1,2,3,4])
print(np.sum(x))
x=np.array([[1,1],[2,2]])
print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))

10
[[1 1]
 [2 2]]
[3 3]
[2 4]


In [45]:
x=np.array([1,3,2])
print(x.min())
print(x.max())
print(x.argmin())
print(x.argmax())

1
3
0
1


Logical operations

In [46]:
np.all([True,True,False])
np.any([True,False,False])
a=np.zeros((50,50))
print(np.any(a!=0))
print(np.all(a==a))
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

False
True


np.True_

Statistics

In [49]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3,4],[5,6,7,8]])
print(x.mean())
print(np.median(x))
print(np.median(y,axis=-1))
x.std()

1.75
1.5
[2.5 6.5]


np.float64(0.82915619758885)

In [51]:
from IPython.core.display_trap import DisplayTrap
import numpy as np
data=np.loadtxt('/content/sample_data/mnist_test.csv',delimiter=',')
data

array([[7., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [4., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.]])